### ISSUE TITLE
Delete workloads pods that are missing an proxy container when they are in an error state

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy-operator#337]
The operator uses a webhook to add the proxy container to pods. The webhook is setup with `failurePolicy: Ignore`. This was an intentional design choice. It allows pods to be created when the operator is not receiving webhook requests.  (If you create a webhook for all pods with `failurePolicy: Fail`, then when the pods serving that webhook are terminated, the cluster will be unable to start new pods, including the replacement pods for that webhook.)

Unfortunately this means that occasionally a pod related to a workload will be created without the operator adding the proxy sidecar container. This could happen if there is a bug in the webhook causing it to return an error response. This could also happen when all the operator pods are offline, for example when the cluster replaces a node which happens to be running all the operator pods. 

The best solution for now is to program the operator to delete improperly configured pods. The operator will listen for events on all pods related to known AuthProxyWorkloads. If such a pod exits in error, the operator will check the pod resource for the proxy sidecar container. If the proxy sidecar container is missing, the operator will delete the pod. 

In the future, we can use the webhook [matchConditions](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchconditions) with `failurePolicy: Fail` to ensure that the webhook only filters pods related to AuthProxyWorklod, not all pods in the cluster. This k8s feature is alpha in v1.27, so we can't use it yet.

**Comment by CoryHagerman** [comment]
Is there something that triggers the process of the controller seeing a pod is in something like a crashloopbackoff that would trigger the deletion and reconciliation process?

If my controller is down when a pod that needs a sidecar injection starts it will not get deleted and then fixed still. 

If I delete the pod myself it does get the sidecar upon starting back up.

**Comment by hessjcg** [comment]
@CoryHagerman The operator should react any time a pod is updated, including status updates.  It seems like it should be reacting to your pods. Is there a way for you to share a snippet of the log from the operator pod?

**Comment by CoryHagerman** [comment]
I discovered a bug and submitted a PR. The issue was the comparison to crashloopbackoff was failing so no pods were reporting issues. 

Pr #387 
Issue #386

**Comment by CoryHagerman** [comment]
It may also be worth noting that there is no logging in the code detecting pods missing sidecars. Could be worth a debug log with the conditions of a failed container that did not match either of the required failure conditions. 

I didn’t want to overstep adding a bunch of logging in my PR.
