### ISSUE TITLE
Feature request: Consider removing generated files from the git repo

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy-operator#368]
Currently our build system check in generated files to the git repository, so that developers would be able to run `go test ./...`
without needing to 

However, after working with this project for a year, it seems like this is more of a hinderance than a help: 

- This prevents automatic version updates of tools that leave their version numbers in the generated files.
- This adds an extra step to the developer workflow for PRs. Developers must run `make generate` before committing code. The tools in the dev environment may be out of date, causing PR checks to fail. 

To fix this, we would remove the following files and list them in `.gitignore`.  No change would be required for PR checks and release builds. Local development instructions would be the same as before: "Run `make build` or `make test`."

```
config/crd/bases/cloudsql.cloud.google.com_authproxyworkloads.yaml
config/samples/cloudsql_v1alpha1_authproxyworkload.yaml
docs/api.md
installer/cloud-sql-proxy-operator.yaml
internal/api/v1/authproxyworkload_types.go
internal/api/v1/zz_generated.deepcopy.go
```

**Comment by ttosta-google** [comment]
We have done this work already. See https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/issues/508.
