### ISSUE TITLE
Support Service Account Authentication 

### ISSUE THREAD

**Issue by jravetch** [GoogleCloudPlatform/cloud-sql-proxy-operator#384]
## Expected Behavior
When using the operator, it only supports workload identity.  Can we please support using a service account?  
```
cloud_sql_proxy -instances="${CLOUDSQL_INSTANCE_NAME}=tcp:5432" -credential_file=credentials.json
```

## Actual Behavior
Only workload identity is supported.  

## Steps to Reproduce the Problem

1. Create secret with service account private key
2. Mount secret as service_account.json
3. Use cloud sql auth proxy operator

## Specifications

- Version: 1.0.1
- Platform: GKE 1.23

**Comment by enocom** [comment]
@jravetch Thanks for the feature request. We generally strongly recommend people use workload identity in Kubernetes, but are open to explore adding support for a service account credentials file.

Out of curiosity, why do you prefer the file based approach?

**Comment by jravetch** [comment]
We use service accounts because the cloud sql instance and the GKE cluster are in two separate projects.  I'm not aware of a way to use workload identity when the cluster and resource are in two different projects.

**Comment by jravetch** [comment]
This issue relates to #43

**Comment by enocom** [comment]
Looks like a duplicate to me.

**Comment by enocom** [comment]
It is possible to use workload identity regardless of project layout.

Let's say you have two projects:

- Project A which hosts your cluster
- Project B which hosts your Cloud SQL Instance.

If you set up workload identity in your cluster, every workload runs as a certain IAM principal. What you do with that IAM principal is entirely up to you. To allow that principal access to Project B, you'd simple add that IAM principal (e.g., `foo@developer.gserviceaccount.com`) into your Project B's members. Once that's done, you probably have to enable the Cloud SQL Admin API in both projects (n.b., it might be only necessary in one project, but I forget if that's true). From there, your cluster can reach your instance in Project B.

If you're using a private IP instance, you'll have to ensure a network path from your cluster to your instance, but that's separate from permissions.

**Comment by jravetch** [comment]
So I was actually able to get workload identity to work across my two projects.  What solved it for me was upgrading the cluster to 1.24.  After the the pods restarted the auth proxy side car was created and was able to connect to the cloud sql db.  Not sure what changed between 1.23 and 1.24.

**Comment by enocom** [comment]
That's good to hear. Generally, we strongly recommend workload identity, but I'll leave this open for folks to chime in if they'd find it useful.

**Comment by enocom** [comment]
Going to close this after all. If folks have a compelling reason for this feature, we're open to considering it, but otherwise strongly recommend workload identity.

**Comment by CoryHagerman** [comment]
Is it possible to use the workload identity in a non GKE cluster? Lets say i deploy my own k8s cluster to gcp compute nodes. Is it possible to still connect that to cloud sql without a credentials file?

**Comment by hessjcg** [comment]
GKE is the best way to run pods with distinct workload identities. However,  it is possible to roll your own K8s and use the workload identity of the VMs. 

All processes running on a GCP VM assume the workload identity of the VM. When you roll your own K8s cluster on GCP VMs, then all the pods in the cluster will assume the identity of the VM on which the pod is running.
