### ISSUE TITLE
failed to connect to instance: Config error: instance does not have IP of type \"PUBLIC\" 

### ISSUE THREAD

**Issue by jravetch** [GoogleCloudPlatform/cloud-sql-proxy-operator#385]
## Expected Behavior
Using the auth proxy operator I should be able to connect to my cloudsql db.  I've setup workload identity and can confirm that workload identity is working.  It should be connecting via the private IP.  Public ip is disabled.  I followed the instructions [here](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#gsa) 

## Actual Behavior
I see the following in the proxy container logs (removed specific project/region/instance names).  Why is it trying to connect over the public ip?
```
{"severity":"INFO","timestamp":"2023-06-27T03:37:11.655Z","message":"[project:region:isntance] accepted connection from 127.0.0.1:39046"}
{"severity":"ERROR","timestamp":"2023-06-27T03:31:27.941Z","message":"[project:region:instance] failed to connect to instance: Config error: instance does not have IP of type \"PUBLIC\" (connection name = \"project:region:instance\")"}
```
## Steps to Reproduce the Problem

1. Create Auth proxy workload spec
2. Create deployment matching workload
3. Auth proxy side car is created 
4. Try to connect to cloud sql db 
```
psql "host=$DB_HOST port=$DB_PORT dbname=$DB_NAME user=$DB_USER"
psql: error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

## Specifications

- Version: 1.0.1
- Platform: GKE 1.24

**Comment by jravetch** [comment]
I realized that the default connection uses the public ip.  
```
PrivateIP (optional) Enable connection to the Cloud SQL instance's private ip for this instance. Default value is false.
```
Once I set `privateIP: true` in the CR, I was able to connect to the db.

**Comment by hessjcg** [comment]
Glad you found a fix. I'll close this issue.
