### ISSUE TITLE
Feature Request: support --quiet option

### ISSUE THREAD

**Issue by thomas-riccardi** [GoogleCloudPlatform/cloud-sql-proxy-operator#402]
## Expected Behavior
have a way to configure `--quiet` (or via env var): no useless logs increasing monitoring costs.
cf https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/1738

## Actual Behavior
currently we get lots of useless INFO logs with connections.

## Specifications

- Version: 1.0.2
- Platform: gke

**Comment by williamcruzme** [comment]
+1
