### ISSUE TITLE
mutatingWebhook is being flagged as unsafe

### ISSUE THREAD

**Issue by serdarkkts** [GoogleCloudPlatform/cloud-sql-proxy-operator#461]
The cloud-sql-proxy-operator mutating webhook can intercept pods in system-managed namespaces. Because of that GKE is flagging the webhook as unsafe.

From the GKE [documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks?&_ga=2.88571228.-693638241.1655217906#unsafe-webhooks): 

> If a webhook is intercepting any resources in system-managed namespaces, or [certain types of resources](https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks?&_ga=2.88571228.-693638241.1655217906#how-gke-detect), GKE considers this unsafe and recommends that you update the webhooks to avoid intercepting these resources.

The recommended action is to change the scope of the resources to `namespaced` from `*` and exclude the system-managed namespaces with the help of the `namespaceSelector` on the `MutatingWebhookConfiguration` resource (Since Kubernetes v1.21). However, I am not sure if this would affect any potential use cases of the cloud-sql-proxy-operator. 

What are your opinions on this?

**Comment by enocom** [comment]
I think this is a bug -- we shouldn't be causing GKE to flag the Operator. Adjusting the priority down, though, as it's not going to interfere with operations.

**Comment by enocom** [comment]
Here's a screenshot of the warning for reference:

![image](https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/assets/1175430/1b4901c9-d3cf-43e0-b615-4beb47323870)

**Comment by enocom** [comment]
Based on GKE's version support, I think v1.21 (April 8, 2021) is already unsupported. So we're good to use a > v1.21 solution here (i.e. namespaceSelector).
