### ISSUE TITLE
Port release process to Kokoro

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy-operator#486]
We need to use Kokoro to build operator releases, as required by security and compliance.

**Comment by ttosta-google** [comment]
This work is done. The version [1.4.4](https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/pull/555) was released using Kokoro.

PR https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/pull/546 to remove the Cloud Run release scripts.
