### ISSUE TITLE
Feature Request: Proxy containers start before application containers

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/cloud-sql-proxy-operator#496]
K8s starts pod containers in the order they are specified, waiting for the post-start hook of a container to complete before moving to the next one. See [Delaying application start until sidecar is ready](https://medium.com/@marko.luksa/delaying-application-start-until-sidecar-is-ready-2ec2d21a7b74) blog post.

Implementation:
- [ ] Add all proxy containers to the beginning of the the list of pod containers, before all the user-defined containers.
- [ ] Add a `postStart` hook to the proxy container that calls the `/ready` hook. This ensures no other containers start until the proxy container is ready.

This will ensure that the proxy container is ready before any other containers are allowed to start in all supported versions of k8s.

**Comment by manueljishi** [comment]
Hi, we are currently having issues with this, are there any plans on taking up this PR?

**Comment by hessjcg** [comment]
Hi @manueljishi, I think we are going to skip this one and only do #381, which will get the same result.

**Comment by manueljishi** [comment]
Perfect @hessjcg thanks a lot!
I will keep an eye on it to see if I can be of any help!

**Comment by hessjcg** [comment]
Closing in favor of #381.
