### ISSUE TITLE
YAML and shell files for release v1.4.4 are missing

### ISSUE THREAD

**Issue by verdel** [GoogleCloudPlatform/cloud-sql-proxy-operator#565]
## Expected Behavior
After the appearance of a new release, all necessary installation files will be placed at `https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy-operator/v1.4.4/`

## Actual Behavior

It appears that during the release process, there was a failure and the files specified in the documentation, required for deployment in Kubernetes, were not placed at `https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy-operator/v1.4.4/`

## Steps to Reproduce the Problem

1. `kubectl apply -f https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy-operator/v1.4.4/cloud-sql-proxy-operator.yaml`
2. `error: unable to read URL "https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy-operator/v1.4.4/cloud-sql-proxy-operator.yaml", server reported 404 Not Found, status code=404`

**Comment by enocom** [comment]
Thanks for the issue, @verdel. We've recently improved our CI/CD infrastructure but must have missed a detail in here. We'll get this fixed ASAP.

**Comment by hessjcg** [comment]
Hi @verdel, 

I have put these files in the correct location. You should be able to continue with your installation now.

**Comment by verdel** [comment]
@hessjcg, thank you very much for the quick response. Now everything works perfectly.
